import { Entity, Article } from './types';

export const initialEntities: Entity[] = [
  {
    id: '1',
    name: 'Obesity',
    type: 'disease',
    x: 150,
    y: 50,
  },
  {
    id: '2',
    name: 'GLP-1 receptor',
    type: 'target',
    x: 150,
    y: 200,
  },
  {
    id: '3',
    name: 'Ozempic',
    type: 'drug',
    x: 150,
    y: 350,
  },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    publicationName: 'A Review on Semaglutide: An Oral Glucagon-Like Peptide 1',
    publicationUrl: 'https://pubmed.ncbi.nlm.nih.gov/example1',
    summary: 'This comprehensive review examines semaglutide, an oral GLP-1 receptor agonist, focusing on its mechanism of action, clinical efficacy, and safety profile in the treatment of type 2 diabetes and obesity.',
    authors: ['Author A', 'Author B', 'Author C', 'Author D'],
    source: 'PubMed | Springer',
    publicationDate: '12.12.2020',
    relevancyScore: 98,
    status: 'Case study',
    similarArticlesCount: 2563,
    citationsCount: 35643,
    isFavorite: false,
  },
  {
    id: '2',
    publicationName: 'Semaglutide, a glucagon like peptide-1 receptor agonist',
    publicationUrl: 'https://pubmed.ncbi.nlm.nih.gov/example2',
    summary: 'Semaglutide demonstrates significant efficacy in weight management and glycemic control through activation of GLP-1 receptors, with notable effects on delayed gastric emptying and potential neuroprotective benefits.',
    authors: ['Author E', 'Author F', 'Author G'],
    source: 'PubMed | Springer',
    publicationDate: '12.12.2020',
    relevancyScore: 98,
    status: 'Case study',
    similarArticlesCount: 2563,
    citationsCount: 35643,
    isFavorite: true,
  },
  {
    id: '3',
    publicationName: 'Pancreatitis Risk Associated with GLP-1 Receptor Agonists',
    publicationUrl: 'https://pubmed.ncbi.nlm.nih.gov/example3',
    summary: 'This study investigates the potential association between GLP-1 receptor agonists and acute pancreatitis risk, analyzing real-world data and clinical trial outcomes to assess safety concerns.',
    authors: ['Author H', 'Author I', 'Author J', 'Author K'],
    source: 'PubMed | Springer',
    publicationDate: '12.12.2020',
    relevancyScore: 95,
    status: 'Case study',
    similarArticlesCount: 1234,
    citationsCount: 15234,
    isFavorite: false,
  },
  {
    id: '4',
    publicationName: 'Once-Weekly Semaglutide in Adults with Overweight or Obesity',
    publicationUrl: 'https://pubmed.ncbi.nlm.nih.gov/example4',
    summary: 'Clinical trial results demonstrating the efficacy of once-weekly semaglutide administration in adults with overweight or obesity, including analysis of adverse effects such as nausea, vomiting, and diarrhea.',
    authors: ['Author L', 'Author M', 'Author N'],
    source: 'PubMed',
    publicationDate: '15.03.2021',
    relevancyScore: 92,
    status: 'Clinical testing',
    similarArticlesCount: 987,
    citationsCount: 8765,
    isFavorite: false,
  },
];

